version: '3.5'

services:
  fingerprint_engine:
    image: dahirmuhammaddahir/grpc_fingerprint_engine
    ports:
      - 4134:4134  # Use a unique port for each service
    restart: unless-stopped
    # Avoid using container_name unless absolutely necessary
    container_name: fingerprint_engine_$(hostname)
    networks:
      - fingerprint_engine_net
  
  fingerprint_client:
    image: r3y3s_fingerprint
    build: .
    ports:
      - 5556:80  # Changed port to avoid conflict
    restart: unless-stopped
    # Avoid using container_name unless absolutely necessary
    container_name: fingerprint_client_$(hostname)
    depends_on:
      - fingerprint_engine
    networks:
      - fingerprint_engine_net
      - fingerprint_client_net

networks:
  fingerprint_engine_net:
  fingerprint_client_net:
