version: '3.5'

services:
  fingerprint_engine:
    image: dahirmuhammaddahir/grpc_fingerprint_engine
    ports:
      - 4135:4135
    restart: unless-stopped
    networks:
      - fingerprint_engine_net
  
  fingerprint_client:
    image: r3y3s_fingerprint
    build: .
    ports:
      - 5557:3030  # Changed port to avoid conflict
    restart: unless-stopped
    depends_on:
      - fingerprint_engine
    networks:
      - fingerprint_engine_net
      - fingerprint_client_net

networks:
  fingerprint_engine_net:
  fingerprint_client_net:
